import Thumbnail2 from './Component/Asserts/blog50.jpg'
import Thumbnail3 from './Component/Asserts/blog51.jpg'
import Thumbnail4 from './Component/Asserts/blog52.jpg'


export const AllData = [
  {
    postID: "2",
    thumbnail: Thumbnail2,
    PostTittle: "Its Very Presious Hand",
    PostParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Est accusamus nesciunt sunt, ipsam aliquid vel dicta laudantium asperiores sed impedit ea obcaecati tenetur, voluptatibus libero, dolorem incidunt. Molestias eligendi quod soluta quia itaque, sapiente magnam consequatur corrupti quibusdam, provident tempore voluptatum fugiat! Eius quaerat repellendus eveniet iusto aspernatur odit consequatur numquam reiciendis debitis alias dignissimos reprehenderit explicabo dicta ducimus, qui ipsam quasi facere eligendi sed nemo quis suscipit harum ab facilis. Quibusdam voluptatibus quas, cum optio debitis accusantium veritatis. Sapiente recusandae itaque laudantium ipsum alias facilis. Labore cumque ex assumenda maxime quia praesentium perferendis aperiam excepturi asperiores at corrupti blanditiis natus, quo possimus dolor alias beatae? Quasi, rerum beatae voluptas architecto voluptates reprehenderit quos assumenda magnam quaerat modi vitae eligendi dolorem veritatis optio maxime repellendus nobis ipsum? Odio, impedit voluptate unde quibusdam voluptatibus deserunt. Maiores provident autem eveniet ullam natus voluptatem officiis neque, tempora nam sapiente adipisci dolor deserunt distinctio eos, ratione in? Quis aliquid tempora doloribus aspernatur recusandae saepe mollitia perferendis ipsum molestias reiciendis nam, laborum eum ut officiis laudantium, ducimus vel corporis debitis voluptate dolore soluta? Fugiat, optio vero. Voluptate architecto voluptates vitae, facere delectus nostrum veniam nihil a officia, earum quis, magni vero consectetur. Cumque, voluptate? Quos, magni aliquid. Repellat sed quia quo qui quae vitae voluptatibus id aperiam odit eaque consequuntur quod explicabo, magni at facilis minus porro animi accusantium quibusdam dolorum. Explicabo natus harum, voluptatem iure aut laudantium voluptatibus assumenda quidem deleniti! Accusantium recusandae praesentium doloremque architecto natus inventore harum quibusdam corrupti eligendi aliquam. Sapiente aliquid consectetur harum dolore? Voluptate quod eveniet aut voluptatibus repellat, maxime, error minima doloremque repellendus assumenda id ea tempore porro amet rerum dolorem aspernatur vitae sint, impedit dolore saepe architecto velit. Excepturi tempore dolore ad minima error animi asperiores, odit aut ab veniam obcaecati eum consequuntur ex. Corporis, rem excepturi!",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex nisi molestias blanditiis similique reiciendis omnis adipisci quo ducimus quia, quam illo accusamus quis consequuntur, tempore harum repellendus suscipit atque cum perferendis fuga quas eaque incidunt dolor? Modi autem, nesciunt dolores nihil distinctio deserunt recusandae praesentium. Sint excepturi, cum adipisci quibusdam facere magnam inventore deleniti enim harum vitae, error velit nihil distinctio veniam. Molestiae praesentium non quidem minus omnis ea exercitationem repudiandae, cumque numquam nostrum voluptatibus vero odio quasi doloribus ullam rerum deserunt earum ab, blanditiis corporis amet cupiditate. Provident eius explicabo, corrupti accusantium ex perferendis. Facere assumenda optio, recusandae, similique nesciunt et, ipsum molestias voluptates quis ad fuga rerum illo consectetur nemo perferendis possimus minima nobis veniam. Reprehenderit temporibus delectus provident fugit repudiandae quia voluptates autem laborum, corrupti perferendis laudantium officia enim amet commodi voluptatibus reiciendis sint? Cumque ducimus fugiat, dolores quos harum nemo pariatur voluptates quasi odio sit aut similique tenetur ipsam voluptate natus commodi impedit. Quibusdam, error est consectetur fugiat inventore nostrum tempora nemo dolore nam commodi tenetur iusto, eligendi accusantium voluptates laudantium repellendus at rerum atque placeat expedita dignissimos aut? Maiores id ipsum illo nulla dolorem tempore excepturi repellat quasi ab, repellendus ea quod blanditiis minima in?"
  },
  {
    postID: "3",
    thumbnail: Thumbnail3,
    PostTittle: "Its Very Presious Hand",
    PostParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Est accusamus nesciunt sunt, ipsam aliquid vel dicta laudantium asperiores sed impedit ea obcaecati tenetur, voluptatibus libero, dolorem incidunt. Molestias eligendi quod soluta quia itaque, sapiente magnam consequatur corrupti quibusdam, provident tempore voluptatum fugiat! Eius quaerat repellendus eveniet iusto aspernatur odit consequatur numquam reiciendis debitis alias dignissimos reprehenderit explicabo dicta ducimus, qui ipsam quasi facere eligendi sed nemo quis suscipit harum ab facilis. Quibusdam voluptatibus quas, cum optio debitis accusantium veritatis. Sapiente recusandae itaque laudantium ipsum alias facilis. Labore cumque ex assumenda maxime quia praesentium perferendis aperiam excepturi asperiores at corrupti blanditiis natus, quo possimus dolor alias beatae? Quasi, rerum beatae voluptas architecto voluptates reprehenderit quos assumenda magnam quaerat modi vitae eligendi dolorem veritatis optio maxime repellendus nobis ipsum? Odio, impedit voluptate unde quibusdam voluptatibus deserunt. Maiores provident autem eveniet ullam natus voluptatem officiis neque, tempora nam sapiente adipisci dolor deserunt distinctio eos, ratione in? Quis aliquid tempora doloribus aspernatur recusandae saepe mollitia perferendis ipsum molestias reiciendis nam, laborum eum ut officiis laudantium, ducimus vel corporis debitis voluptate dolore soluta? Fugiat, optio vero. Voluptate architecto voluptates vitae, facere delectus nostrum veniam nihil a officia, earum quis, magni vero consectetur. Cumque, voluptate? Quos, magni aliquid. Repellat sed quia quo qui quae vitae voluptatibus id aperiam odit eaque consequuntur quod explicabo, magni at facilis minus porro animi accusantium quibusdam dolorum. Explicabo natus harum, voluptatem iure aut laudantium voluptatibus assumenda quidem deleniti! Accusantium recusandae praesentium doloremque architecto natus inventore harum quibusdam corrupti eligendi aliquam. Sapiente aliquid consectetur harum dolore? Voluptate quod eveniet aut voluptatibus repellat, maxime, error minima doloremque repellendus assumenda id ea tempore porro amet rerum dolorem aspernatur vitae sint, impedit dolore saepe architecto velit. Excepturi tempore dolore ad minima error animi asperiores, odit aut ab veniam obcaecati eum consequuntur ex. Corporis, rem excepturi!",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex nisi molestias blanditiis similique reiciendis omnis adipisci quo ducimus quia, quam illo accusamus quis consequuntur, tempore harum repellendus suscipit atque cum perferendis fuga quas eaque incidunt dolor? Modi autem, nesciunt dolores nihil distinctio deserunt recusandae praesentium. Sint excepturi, cum adipisci quibusdam facere magnam inventore deleniti enim harum vitae, error velit nihil distinctio veniam. Molestiae praesentium non quidem minus omnis ea exercitationem repudiandae, cumque numquam nostrum voluptatibus vero odio quasi doloribus ullam rerum deserunt earum ab, blanditiis corporis amet cupiditate. Provident eius explicabo, corrupti accusantium ex perferendis. Facere assumenda optio, recusandae, similique nesciunt et, ipsum molestias voluptates quis ad fuga rerum illo consectetur nemo perferendis possimus minima nobis veniam. Reprehenderit temporibus delectus provident fugit repudiandae quia voluptates autem laborum, corrupti perferendis laudantium officia enim amet commodi voluptatibus reiciendis sint? Cumque ducimus fugiat, dolores quos harum nemo pariatur voluptates quasi odio sit aut similique tenetur ipsam voluptate natus commodi impedit. Quibusdam, error est consectetur fugiat inventore nostrum tempora nemo dolore nam commodi tenetur iusto, eligendi accusantium voluptates laudantium repellendus at rerum atque placeat expedita dignissimos aut? Maiores id ipsum illo nulla dolorem tempore excepturi repellat quasi ab, repellendus ea quod blanditiis minima in?"
  },
  {
    postID: "4",
    thumbnail: Thumbnail4,
    PostTittle: "Its Very Presious Hand",
    PostParagraph: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Est accusamus nesciunt sunt, ipsam aliquid vel dicta laudantium asperiores sed impedit ea obcaecati tenetur, voluptatibus libero, dolorem incidunt. Molestias eligendi quod soluta quia itaque, sapiente magnam consequatur corrupti quibusdam, provident tempore voluptatum fugiat! Eius quaerat repellendus eveniet iusto aspernatur odit consequatur numquam reiciendis debitis alias dignissimos reprehenderit explicabo dicta ducimus, qui ipsam quasi facere eligendi sed nemo quis suscipit harum ab facilis. Quibusdam voluptatibus quas, cum optio debitis accusantium veritatis. Sapiente recusandae itaque laudantium ipsum alias facilis. Labore cumque ex assumenda maxime quia praesentium perferendis aperiam excepturi asperiores at corrupti blanditiis natus, quo possimus dolor alias beatae? Quasi, rerum beatae voluptas architecto voluptates reprehenderit quos assumenda magnam quaerat modi vitae eligendi dolorem veritatis optio maxime repellendus nobis ipsum? Odio, impedit voluptate unde quibusdam voluptatibus deserunt. Maiores provident autem eveniet ullam natus voluptatem officiis neque, tempora nam sapiente adipisci dolor deserunt distinctio eos, ratione in? Quis aliquid tempora doloribus aspernatur recusandae saepe mollitia perferendis ipsum molestias reiciendis nam, laborum eum ut officiis laudantium, ducimus vel corporis debitis voluptate dolore soluta? Fugiat, optio vero. Voluptate architecto voluptates vitae, facere delectus nostrum veniam nihil a officia, earum quis, magni vero consectetur. Cumque, voluptate? Quos, magni aliquid. Repellat sed quia quo qui quae vitae voluptatibus id aperiam odit eaque consequuntur quod explicabo, magni at facilis minus porro animi accusantium quibusdam dolorum. Explicabo natus harum, voluptatem iure aut laudantium voluptatibus assumenda quidem deleniti! Accusantium recusandae praesentium doloremque architecto natus inventore harum quibusdam corrupti eligendi aliquam. Sapiente aliquid consectetur harum dolore? Voluptate quod eveniet aut voluptatibus repellat, maxime, error minima doloremque repellendus assumenda id ea tempore porro amet rerum dolorem aspernatur vitae sint, impedit dolore saepe architecto velit. Excepturi tempore dolore ad minima error animi asperiores, odit aut ab veniam obcaecati eum consequuntur ex. Corporis, rem excepturi!",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex nisi molestias blanditiis similique reiciendis omnis adipisci quo ducimus quia, quam illo accusamus quis consequuntur, tempore harum repellendus suscipit atque cum perferendis fuga quas eaque incidunt dolor? Modi autem, nesciunt dolores nihil distinctio deserunt recusandae praesentium. Sint excepturi, cum adipisci quibusdam facere magnam inventore deleniti enim harum vitae, error velit nihil distinctio veniam. Molestiae praesentium non quidem minus omnis ea exercitationem repudiandae, cumque numquam nostrum voluptatibus vero odio quasi doloribus ullam rerum deserunt earum ab, blanditiis corporis amet cupiditate. Provident eius explicabo, corrupti accusantium ex perferendis. Facere assumenda optio, recusandae, similique nesciunt et, ipsum molestias voluptates quis ad fuga rerum illo consectetur nemo perferendis possimus minima nobis veniam. Reprehenderit temporibus delectus provident fugit repudiandae quia voluptates autem laborum, corrupti perferendis laudantium officia enim amet commodi voluptatibus reiciendis sint? Cumque ducimus fugiat, dolores quos harum nemo pariatur voluptates quasi odio sit aut similique tenetur ipsam voluptate natus commodi impedit. Quibusdam, error est consectetur fugiat inventore nostrum tempora nemo dolore nam commodi tenetur iusto, eligendi accusantium voluptates laudantium repellendus at rerum atque placeat expedita dignissimos aut? Maiores id ipsum illo nulla dolorem tempore excepturi repellat quasi ab, repellendus ea quod blanditiis minima in?"
  },
];
